version: "3"

services:
  sonarqube:
    image: sonarqube:community
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - sonar.forceAuthentication=false

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
    depends_on:
      - mongodb
